package com.userdata.emailservice.services;

import com.userdata.emailservice.models.UserData;
import java.util.List;

public class EmailTemplateBuilder {

    public static String createEmailHtml(List<UserData> userDataList) {
        StringBuilder html = new StringBuilder();

        html.append("<!DOCTYPE html>");
        html.append("<html lang=\"en\">");
        html.append("<head>");
        html.append("<meta charset=\"UTF-8\">");
        html.append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
        html.append("<title>User Data Report</title>");
        html.append("<style>");
        html.append("body { font-family: Arial, sans-serif; background-color: #f4f4f4; margin: 0; padding: 20px; }");
        html.append(".container { max-width: 800px; margin: 0 auto; background-color: white; padding: 30px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }");
        html.append("h1 { color: #4A90E2; text-align: center; margin-bottom: 10px; }");
        html.append(".subtitle { text-align: center; color: #666; margin-bottom: 30px; }");
        html.append("table { width: 100%; border-collapse: collapse; margin-top: 20px; }");
        html.append("th { background-color: #4A90E2; color: white; padding: 12px; text-align: left; font-weight: bold; }");
        html.append("td { padding: 10px; border-bottom: 1px solid #ddd; }");
        html.append("tr:hover { background-color: #f5f5f5; }");
        html.append("tr:nth-child(even) { background-color: #f9f9f9; }");
        html.append(".footer { text-align: center; margin-top: 30px; padding-top: 20px; border-top: 2px solid #4A90E2; color: #666; font-size: 14px; }");
        html.append(".record-count { text-align: center; color: #666; margin-bottom: 20px; font-size: 16px; }");
        html.append(".empty-state { text-align: center; padding: 40px; color: #999; }");
        html.append("</style>");
        html.append("</head>");
        html.append("<body>");
        html.append("<div class=\"container\">");
        
        html.append("<h1>📊 User Data Report</h1>");
        html.append("<p class=\"subtitle\">Complete database records</p>");
        
        if (userDataList == null || userDataList.isEmpty()) {
            html.append("<div class=\"empty-state\">");
            html.append("<p>No user data available at this time.</p>");
            html.append("</div>");
        } else {
            html.append("<p class=\"record-count\">");
            html.append("<strong>Total Records: " + userDataList.size() + "</strong>");
            html.append("</p>");
            
            html.append("<table>");
            html.append("<thead>");
            html.append("<tr>");
            html.append("<th>ID</th>");
            html.append("<th>Name</th>");
            html.append("<th>Age</th>");
            html.append("<th>Created At</th>");
            html.append("<th>Email</th>");
            html.append("</tr>");
            html.append("</thead>");
            html.append("<tbody>");
            
            for (UserData userData : userDataList) {
                html.append("<tr>");
                html.append("<td>").append(userData.getId()).append("</td>");
                html.append("<td>").append(escapeHtml(userData.getName())).append("</td>");
                html.append("<td>").append(userData.getAge()).append("</td>");
                html.append("<td>").append(userData.getFormattedCreatedAt()).append("</td>");
                
                String email = userData.getEmail();
                if (email != null && !email.trim().isEmpty()) {
                    html.append("<td>").append(escapeHtml(email)).append("</td>");
                } else {
                    html.append("<td style=\"color: #999; font-style: italic;\">N/A</td>");
                }
                
                html.append("</tr>");
            }
            
            html.append("</tbody>");
            html.append("</table>");
        }
        
        html.append("<div class=\"footer\">");
        html.append("<p>This is an automated report generated by the User Data System</p>");
        html.append("<p>Powered by Azure Communication Service</p>");
        html.append("</div>");
        
        html.append("</div>");
        html.append("</body>");
        html.append("</html>");

        return html.toString();
    }

    private static String escapeHtml(String text) {
        if (text == null) {
            return "";
        }
        return text.replace("&", "&amp;")
                   .replace("<", "&lt;")
                   .replace(">", "&gt;")
                   .replace("\"", "&quot;")
                   .replace("'", "&#39;");
    }
}
